name: CI/CD Pipeline for Dockerized App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Docker Buildx for building multi-platform Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (You need to add your Docker Hub credentials as GitHub secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username:  biplavm 
          password:  biplav001 

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t biplavm/my-next-app:$GITHUB_SHA .

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push biplavm/my-next-app:$GITHUB_SHA

  test:
    runs-on: ubuntu-latest
    needs: build  # This ensures tests run after the build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Run tests inside the Docker container (you can modify the command based on your testing setup)
      - name: Run Tests in Docker Container
        run: |
          docker run -d --name test-container biplavm/my-next-app:$GITHUB_SHA
          docker exec test-container npm run test
          docker stop test-container
